libs =
import libs += libbzip2%lib{bzip2}


./ : exe{bzip2}: libue{bzip2} testscript
./ : exe{bunzip2}: libue{bzip2}
./ : exe{bzcat}: libue{bzip2}

libue{bzip2}: {h c}{**} $libs

c.poptions =+ "-I$out_root" "-I$src_root"

./ : file{test/*}
file{*} :
{
    install = false
    dist = true
}