libs =
import libs += libbzip2%lib{bzip2}


./ : exe{bzip2}: libue{bzip2} testscript
./ : exe{bunzip2}: libue{bzip2}
./ : exe{bzcat}: libue{bzip2}

libue{bzip2}: {h c}{**} $libs

c.poptions =+ "-I$out_root" "-I$src_root"

# Warnings cleanup
switch $c.class, $c.target.class
{
  case 'msvc'
    obj{*}: cc.poptions += -D_CRT_SECURE_NO_WARNINGS

  case 'gcc', 'windows'
    obj{*}: cc.poptions += -Wno-deprecated
}

./ : file{test/*}
file{*} :
{
    install = false
    dist = true
}
