libs =
#import libs += libhello%lib{hello}

exe{bzip2recover}: {h c}{**} $libs

c.poptions =+ "-I$out_root" "-I$src_root"

# Warnings cleanup
switch $c.class, $c.target.class
{
  case 'msvc'
    obj{*}: cc.poptions += -D_CRT_SECURE_NO_WARNINGS

  case 'gcc', 'windows'
    obj{*}: cc.poptions += -Wno-deprecated
}
